app = "ibft-catpics"

[build]
    dockerfile = "Dockerfile"

[env]
  PORT = "3000"  # Important: Many Node apps read PORT from env

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"